---
editor: source
---

# Vorwort {.unnumbered}
## Bemerkungen

Dieses GitHub-Repository enthält das Vorlesungsskript zur Vorlesung "Gravimetrie" im Rahmen des Moduls "Gravimetrie und Magnetik" im Wintersemester 2025/26.
Das Modul ist für Studierende des Bachelorstudienganges "Geophysik und Geoinformatik" an der TU Bergakademie Freiberg entworfen.

## Code

Das Kursmaterial auf der Website enthält Abschnitte mit eingebettetem Python-Code.

Sie können den Code kopieren und in einer kompatiblen Python- oder Julia-Umgebung ausführen.

Für optimales Arbeiten und Lernen wird empfohlen, Python über [miniforge](https://conda-forge.org/download/) zu installieren.

Darüber hinaus haben Sie die Möglichkeit, eigene Konzepte zu erkunden, indem Sie eigene Jupyter-Notebooks erstellen. Dabei können Sie eine der folgenden Plattformen verwenden:

- [Visual Studio Code](https://code.visualstudio.com/)
- [JupyterLab](https://jupyter.org/)
- [Quarto](https://quarto.org/)
- [marimo](https://marimo.io/)
    
Die Arbeit mit Jupyter-Notebooks in Visual Studio Code ist [besonders unkompliziert](https://code.visualstudio.com/docs/datascience/jupyter-notebooks).

## Selbststudium

Es gibt kleine Übungsaufgaben, die über die Vorlesung verteilt sind.

::: {.callout title="Self study"}
Diese Aufgaben sind leicht zu erkennen.
:::

## Referenzen

Dieses Skript basiert zum großen Teil auf Lehrmaterialien, welche mir freundlicherweise von meinen ehemaligen Kollegen Rolf Käppler und Jana Börner zur Verfügung gestellt wurden.

## Lizenz

Das Material steht unter der Creative Commons Lizenz.